name: profile
description: "Flutter web profile"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^1.5.1
  google_fonts: ^6.2.1
  animations: ^2.0.11
  loading_gifs: ^0.3.0
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.9
  url_launcher_web: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/
    - assets/svg/
  uses-material-design: true
